const $=id=>document.getElementById(id), n=id=>Number($(id)?.value||0), money=x=>'₹'+Number(x||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const R=h=>$('result').innerHTML=h, S=(k,v)=>localStorage.setItem('wz_'+k,JSON.stringify(v)), L=(k,d=[])=>{try{return JSON.parse(localStorage.getItem('wz_'+k))??d}catch{return d}};
const F=(id,label,type='number',ph='')=>`<div><label>${label}</label><input id="${id}" type="${type}" placeholder="${ph}"></div>`;
const TA=(id,label,ph='')=>`<div style="grid-column:1/-1"><label>${label}</label><textarea id="${id}" placeholder="${ph}"></textarea></div>`;
const SEL=(id,label,opts)=>`<div><label>${label}</label><select id="${id}">${opts.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></div>`;
const ui=(fields,actions='calc')=>{ $('fields').innerHTML=fields.join(''); $('actions').innerHTML=actions==='calc'?'<button onclick="calc()">Calculate</button><button class="secondary" onclick="reset()">Reset</button>':actions; };
function reset(){document.querySelectorAll('#fields input,#fields textarea').forEach(x=>x.value='');R('Enter values above and calculate.')} function mins(v){let[a,b]=v.split(':').map(Number);return a*60+b}
let timer=null,left=0,sw=0;
const slug=window.WORKZIVO_SLUG;
if(slug==='monthly-budget-planner'){ui([F('income','Monthly Income'),F('rent','Rent / Housing'),F('food','Food / Grocery'),F('transport','Transport / Fuel'),F('bills','Bills / Recharge'),F('emi','EMI / Debt'),F('other','Other Expenses'),F('goal','Savings Goal')]);window.calc=()=>{let i=n('income'),e=n('rent')+n('food')+n('transport')+n('bills')+n('emi')+n('other'),r=i-e;R(`<b>Total expenses:</b> ${money(e)}<br><b>Remaining:</b> ${money(r)}<br><b>Savings rate:</b> ${i?(r/i*100).toFixed(2):0}%<br><b>Status:</b> ${r>=n('goal')?'Goal achievable':'Below savings goal'}`)}}
else if(slug==='bill-splitter'||slug==='home-expense-splitter'||slug==='taxi-fare-splitter'){let home=slug==='home-expense-splitter',taxi=slug==='taxi-fare-splitter';ui(home?[F('a','Rent'),F('b','Bills'),F('c','Groceries'),F('p','People')]:taxi?[F('a','Taxi Fare'),F('b','Extra Charges'),F('p','People')]:[F('a','Bill Amount'),F('p','People')]);window.calc=()=>{let t=n('a')+n('b')+n('c'),p=n('p');R(p>0?`<b>Total:</b> ${money(t)}<br><b>Per person:</b> ${money(t/p)}`:'Enter number of people.')}}
else if(slug==='tip-calculator'){ui([F('bill','Bill Amount'),F('tip','Tip %')]);window.calc=()=>{let b=n('bill'),t=b*n('tip')/100;R(`<b>Tip:</b> ${money(t)}<br><b>Total:</b> ${money(b+t)}`)}}
else if(slug==='fuel-cost-calculator'){ui([F('d','Distance (km)'),F('m','Mileage (km/l)'),F('p','Fuel Price / litre')]);window.calc=()=>{let m=n('m');R(m>0?`<b>Fuel needed:</b> ${(n('d')/m).toFixed(2)} L<br><b>Cost:</b> ${money(n('d')/m*n('p'))}`:'Mileage must be greater than 0.')}}
else if(slug==='price-comparison-calculator'){ui([F('p1','Product A Price'),F('q1','Product A Quantity'),F('p2','Product B Price'),F('q2','Product B Quantity')]);window.calc=()=>{let a=n('p1')/n('q1'),b=n('p2')/n('q2');R(isFinite(a)&&isFinite(b)?`<b>A/unit:</b> ${money(a)}<br><b>B/unit:</b> ${money(b)}<br><b>Better value:</b> ${a<b?'A':b<a?'B':'Same'}`:'Enter valid quantities.')}}
else if(slug==='savings-goal-planner'){ui([F('t','Target'),F('c','Current Savings'),F('m','Months')]);window.calc=()=>{let m=n('m'),x=Math.max(0,n('t')-n('c'));R(m>0?`<b>Still needed:</b> ${money(x)}<br><b>Per month:</b> ${money(x/m)}`:'Months must be at least 1.')}}
else if(slug==='electricity-bill-estimator'){ui([F('u','Units'),F('r','Rate per Unit'),F('f','Fixed Charges')]);window.calc=()=>R(`<b>Estimated bill:</b> ${money(n('u')*n('r')+n('f'))}<br><span class="small">Flat-rate estimate; actual slab charges may differ.</span>`)}
else if(slug==='simple-interest-calculator'){ui([F('p','Principal'),F('r','Annual Rate %'),F('y','Years')]);window.calc=()=>{let p=n('p'),i=p*n('r')*n('y')/100;R(`<b>Interest:</b> ${money(i)}<br><b>Total:</b> ${money(p+i)}`)}}
else if(slug==='compound-interest-calculator'){ui([F('p','Principal'),F('r','Annual Rate %'),F('y','Years'),F('f','Compounds / Year')]);window.calc=()=>{let f=n('f');if(f<1)return R('Frequency must be at least 1.');let p=n('p'),a=p*Math.pow(1+n('r')/100/f,f*n('y'));R(`<b>Final amount:</b> ${money(a)}<br><b>Interest:</b> ${money(a-p)}`)}}
else if(slug==='mileage-calculator'){ui([F('d','Distance (km)'),F('f','Fuel Used (litres)')]);window.calc=()=>R(n('f')>0?`<b>Mileage:</b> ${(n('d')/n('f')).toFixed(2)} km/l`:'Fuel must be greater than 0.')}
else if(slug==='trip-expense-calculator'||slug==='travel-budget-planner'){let b=slug==='travel-budget-planner';ui((b?[F('budget','Total Budget')]:[]).concat([F('a','Travel / Tickets'),F('b','Stay / Hotel'),F('c','Food'),F('d','Local / Other')]));window.calc=()=>{let t=n('a')+n('b')+n('c')+n('d');R(b?`<b>Estimated spend:</b> ${money(t)}<br><b>Remaining:</b> ${money(n('budget')-t)}<br><b>Status:</b> ${t<=n('budget')?'Within budget':'Over budget'}`:`<b>Total trip cost:</b> ${money(t)}`)}}
else if(slug==='work-hours-calculator'||slug==='shift-hours-calculator'){ui([F('s','Start Time','time'),F('e','End Time','time')].concat(slug==='shift-hours-calculator'?[F('b','Break Minutes')]:[]));window.calc=()=>{if(!$('s').value||!$('e').value)return R('Choose both times.');let d=mins($('e').value)-mins($('s').value);if(d<0)d+=1440;d=Math.max(0,d-n('b'));R(`<b>Duration:</b> ${Math.floor(d/60)} h ${d%60} min`)}}
else if(slug==='overtime-calculator'){ui([F('h','Total Hours'),F('r','Regular Hours'),F('rate','Hourly Rate'),F('m','Overtime Multiplier')]);window.calc=()=>{let ot=Math.max(0,n('h')-n('r')),mul=n('m')||1.5;R(`<b>Overtime:</b> ${ot.toFixed(2)} h<br><b>Estimated pay:</b> ${money(ot*n('rate')*mul)}`)}}
else if(slug==='meeting-cost-calculator'){ui([F('p','Attendees'),F('r','Average Hourly Cost / Person'),F('m','Meeting Duration (minutes)')]);window.calc=()=>R(`<b>Estimated meeting cost:</b> ${money(n('p')*n('r')*n('m')/60)}`)}
else if(slug==='daily-productivity-tracker'){ui([F('p','Tasks Planned'),F('d','Tasks Completed')]);window.calc=()=>R(n('p')>0?`<b>Productivity:</b> ${Math.min(100,n('d')/n('p')*100).toFixed(2)}%`:'Planned tasks must be at least 1.')}
else if(slug==='bmi-calculator'){ui([F('w','Weight (kg)'),F('h','Height (cm)')]);window.calc=()=>{let h=n('h')/100,b=n('w')/(h*h),c=b<18.5?'Underweight':b<25?'Normal range':b<30?'Overweight':'Obesity range';R(h>0?`<b>BMI:</b> ${b.toFixed(1)}<br><b>Category:</b> ${c}<br><span class="small">General screening estimate, not medical advice.</span>`:'Enter valid height.')}}
else if(slug==='calorie-needs-estimator'){ui([SEL('sex','Sex',[['male','Male'],['female','Female']]),F('age','Age'),F('w','Weight (kg)'),F('h','Height (cm)'),SEL('act','Activity',[['1.2','Sedentary'],['1.375','Light'],['1.55','Moderate'],['1.725','Very active']])]);window.calc=()=>{let b=10*n('w')+6.25*n('h')-5*n('age')+($('sex').value==='male'?5:-161);R(`<b>Estimated daily calories:</b> ${Math.round(b*Number($('act').value))} kcal/day<br><span class="small">General estimate, not medical advice.</span>`)}}
else if(slug==='steps-distance-calculator'){ui([F('s','Steps'),F('l','Stride Length (cm)')]);window.calc=()=>R(`<b>Estimated distance:</b> ${(n('s')*n('l')/100000).toFixed(2)} km`)}
else if(slug==='pace-calculator'){ui([F('d','Distance (km)'),F('h','Hours'),F('m','Minutes'),F('s','Seconds')]);window.calc=()=>{let d=n('d'),p=(n('h')*3600+n('m')*60+n('s'))/d;if(d<=0)return R('Distance must be greater than 0.');let mm=Math.floor(p/60),ss=Math.round(p%60);if(ss===60){mm++;ss=0}R(`<b>Pace:</b> ${mm}:${String(ss).padStart(2,'0')} min/km`)}}
else if(slug==='kitchen-unit-converter'){ui([F('v','Value'),SEL('from','From',[['cup','Cup'],['tbsp','Tablespoon'],['tsp','Teaspoon'],['ml','Millilitre']]),SEL('to','To',[['ml','Millilitre'],['cup','Cup'],['tbsp','Tablespoon'],['tsp','Teaspoon']])]);window.calc=()=>{let x={cup:240,tbsp:15,tsp:5,ml:1};R(`<b>Converted:</b> ${(n('v')*x[$('from').value]/x[$('to').value]).toFixed(2)} ${$('to').value}`)}}
else if(slug==='recipe-quantity-calculator'){ui([F('q','Original Quantity'),F('o','Original Servings'),F('n','New Servings')]);window.calc=()=>R(n('o')>0?`<b>New quantity:</b> ${(n('q')*n('n')/n('o')).toFixed(2)}`:'Original servings must be at least 1.')}
else if(slug==='grocery-unit-price-calculator'){ui([F('p','Price'),F('q','Quantity'),F('u','Unit Name','text','kg / litre / piece')]);window.calc=()=>R(n('q')>0?`<b>Price per ${$('u').value||'unit'}:</b> ${money(n('p')/n('q'))}`:'Quantity must be greater than 0.')}
else if(slug==='event-countdown'){ui([F('name','Event Name','text','Birthday'),F('date','Event Date & Time','datetime-local')]);window.calc=()=>{let t=new Date($('date').value)-Date.now();if(!isFinite(t)||t<=0)return R('Choose a future date.');R(`<b>${$('name').value||'Event'}:</b> ${Math.floor(t/86400000)} days, ${Math.floor(t%86400000/3600000)} hours, ${Math.floor(t%3600000/60000)} minutes`)}}
else if(slug==='sleep-calculator'){ui([SEL('mode','Calculate',[['wake','Bedtime from wake time'],['bed','Wake time from bedtime']]),F('time','Time','time')]);window.calc=()=>{if(!$('time').value)return R('Choose a time.');let[h,m]=$('time').value.split(':').map(Number),d=new Date();d.setHours(h,m,0,0);d=new Date(d.getTime()+($('mode').value==='wake'?-450:450)*60000);R(`<b>Estimated ${$('mode').value==='wake'?'bedtime':'wake time'}:</b> ${d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`)}}
else if(slug==='pomodoro-timer'||slug==='cooking-timer'){ui([F('m','Minutes','number',slug==='pomodoro-timer'?'25':'10')],'<button onclick="startT()">Start</button><button class="secondary" onclick="stopT()">Stop</button><button class="secondary" onclick="resetT()">Reset</button>');window.show=()=>R(`<b>${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}</b>`);window.startT=()=>{if(timer)return;if(!left)left=(n('m')||25)*60;timer=setInterval(()=>{left--;show();if(left<=0){clearInterval(timer);timer=null;alert('Timer complete!')}},1000);show()};window.stopT=()=>{clearInterval(timer);timer=null};window.resetT=()=>{stopT();left=(n('m')||(slug==='pomodoro-timer'?25:10))*60;show()};resetT()}
else if(slug==='stopwatch'){ui([],'<button onclick="startSW()">Start</button><button class="secondary" onclick="stopSW()">Stop</button><button class="secondary" onclick="resetSW()">Reset</button>');window.show=()=>R(`<b>${String(Math.floor(sw/3600)).padStart(2,'0')}:${String(Math.floor(sw%3600/60)).padStart(2,'0')}:${String(sw%60).padStart(2,'0')}</b>`);window.startSW=()=>{if(timer)return;timer=setInterval(()=>{sw++;show()},1000)};window.stopSW=()=>{clearInterval(timer);timer=null};window.resetSW=()=>{stopSW();sw=0;show()};show()}
else if(slug==='random-decision-picker'){ui([TA('opts','Options (one per line)','Pizza\nBurger\nSandwich')],'<button onclick="pick()">Pick Random</button>');window.pick=()=>{let a=$('opts').value.split(/\n|,/).map(x=>x.trim()).filter(Boolean);R(a.length?`<b>Picked:</b> ${a[Math.floor(Math.random()*a.length)]}`:'Add at least one option.')}}
else if(['daily-expense-tracker','grocery-list-budget','habit-tracker','to-do-list','travel-packing-checklist','weight-progress-tracker','quick-notes','water-intake-tracker'].includes(slug)){
 if(slug==='quick-notes'){ui([TA('note','Note','Write your note here...')],'<button onclick="saveNote()">Save Note</button><button class="secondary" onclick="clearNote()">Clear</button>');$('note').value=L('note','');window.saveNote=()=>{S('note',$('note').value);R('Note saved on this device.')};window.clearNote=()=>{$('note').value='';S('note','');R('Note cleared.')}}
 else if(slug==='water-intake-tracker'){ui([F('goal','Daily Goal (ml)'),F('amt','Add Water (ml)')],'<button onclick="addWater()">Add Water</button><button class="secondary" onclick="clearWater()">Reset</button>');let render=()=>{let d=L('water',{total:0,goal:2500});$('goal').value=d.goal;R(`<b>${d.total} ml</b> of ${d.goal} ml (${Math.min(100,d.total/d.goal*100).toFixed(0)}%)`)};window.addWater=()=>{let d=L('water',{total:0,goal:2500});d.goal=n('goal')||d.goal;d.total+=n('amt');S('water',d);$('amt').value='';render()};window.clearWater=()=>{S('water',{total:0,goal:n('goal')||2500});render()};render()}
 else {let isMoney=['daily-expense-tracker','grocery-list-budget'].includes(slug), isWeight=slug==='weight-progress-tracker';ui(isMoney?[F('name',slug==='daily-expense-tracker'?'Expense Note':'Item','text'),F('val','Amount')]:isWeight?[F('val','Weight (kg)')]:[F('name',slug==='travel-packing-checklist'?'Packing Item':slug==='habit-tracker'?'Habit':'Task','text')],'<button onclick="addItem()">Add</button><button class="secondary" onclick="clearItems()">Clear All</button>');let key='list_'+slug,render=()=>{let a=L(key,[]);R(a.length?a.map((x,i)=>`<div class="item"><span>${x.done?'✅ ':''}${x.name||x.date||''}</span><span>${x.val!=null?(isWeight?x.val+' kg':money(x.val)):''} <button onclick="toggleItem(${i})">${isMoney||isWeight?'Remove':(x.done?'Undo':'Done')}</button></span></div>`).join(''):'No entries yet.')};window.addItem=()=>{let a=L(key,[]),obj=isWeight?{date:new Date().toLocaleDateString(),val:n('val')}:{name:$('name').value.trim(),val:isMoney?n('val'):undefined,done:false};if((!isWeight&&!obj.name)||(isWeight&&obj.val<=0))return; a.push(obj);S(key,a);document.querySelectorAll('#fields input').forEach(x=>x.value='');render()};window.toggleItem=i=>{let a=L(key,[]);if(isMoney||isWeight)a.splice(i,1);else a[i].done=!a[i].done;S(key,a);render()};window.clearItems=()=>{S(key,[]);render()};render()}}
}
else {ui([F('a','Value 1'),F('b','Value 2')]);window.calc=()=>R(`<b>Result:</b> ${n('a')+n('b')}`)}
